In [60]:
!pip install pandas --quiet
import pandas as pd

In [61]:
df=pd.read_csv("phishing.csv")

In [62]:
df.describe()

,length_url,length_hostname,ip,nb_dots,nb_hyphens,nb_at,nb_qm,nb_and,nb_or,nb_eq,...,empty_title,domain_in_title,domain_with_copyright,whois_registered_domain,domain_registration_length,domain_age,web_traffic,dns_record,google_index,page_rank
count,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.0,11430.000000,...,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,11430.000000,1.143000e+04,11430.000000,11430.000000,11430.000000
mean,61.126684,21.090289,0.150569,2.480752,0.997550,0.022222,0.141207,0.162292,0.0,0.293176,...,0.124759,0.775853,0.439545,0.072878,492.532196,4062.543745,8.567566e+05,0.020122,0.533946,3.185739
std,55.297318,10.777171,0.357644,1.369686,2.087087,0.155500,0.364456,0.821337,0.0,0.998317,...,0.330460,0.417038,0.496353,0.259948,814.769415,3107.784600,1.995606e+06,0.140425,0.498868,2.536955
min,12.000000,4.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,-1.000000,-12.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,33.000000,15.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,1.000000,0.000000,0.000000,84.000000,972.250000,0.000000e+00,0.000000,0.000000,1.000000
50%,47.000000,19.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,1.000000,0.000000,0.000000,242.000000,3993.000000,1.651000e+03,0.000000,1.000000,3.000000
75%,71.000000,24.000000,0.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.000000,1.000000,1.000000,0.000000,449.000000,7026.750000,3.738455e+05,0.000000,1.000000,5.000000
max,1641.000000,214.000000,1.000000,24.000000,43.000000,4.000000,3.000000,19.000000,0.0,19.000000,...,1.000000,1.000000,1.000000,1.000000,29829.000000,12874.000000,1.076799e+07,1.000000,1.000000,10.000000

In [63]:
df.columns

Index(['url', 'length_url', 'length_hostname', 'ip', 'nb_dots', 'nb_hyphens',
       'nb_at', 'nb_qm', 'nb_and', 'nb_or', 'nb_eq', 'nb_underscore',
       'nb_tilde', 'nb_percent', 'nb_slash', 'nb_star', 'nb_colon', 'nb_comma',
       'nb_semicolumn', 'nb_dollar', 'nb_space', 'nb_www', 'nb_com',
       'nb_dslash', 'http_in_path', 'https_token', 'ratio_digits_url',
       'ratio_digits_host', 'punycode', 'port', 'tld_in_path',
       'tld_in_subdomain', 'abnormal_subdomain', 'nb_subdomains',
       'prefix_suffix', 'random_domain', 'shortening_service',
       'path_extension', 'nb_redirection', 'nb_external_redirection',
       'length_words_raw', 'char_repeat', 'shortest_words_raw',
       'shortest_word_host', 'shortest_word_path', 'longest_words_raw',
       'longest_word_host', 'longest_word_path', 'avg_words_raw',
       'avg_word_host', 'avg_word_path', 'phish_hints', 'domain_in_brand',
       'brand_in_subdomain', 'brand_in_path', 'suspecious_tld',
       'statistical_report', 'nb_hyperlinks', 'ratio_intHyperlinks',
       'ratio_extHyperlinks', 'ratio_nullHyperlinks', 'nb_extCSS',
       'ratio_intRedirection', 'ratio_extRedirection', 'ratio_intErrors',
       'ratio_extErrors', 'login_form', 'external_favicon', 'links_in_tags',
       'submit_email', 'ratio_intMedia', 'ratio_extMedia', 'sfh', 'iframe',
       'popup_window', 'safe_anchor', 'onmouseover', 'right_clic',
       'empty_title', 'domain_in_title', 'domain_with_copyright',
       'whois_registered_domain', 'domain_registration_length', 'domain_age',
       'web_traffic', 'dns_record', 'google_index', 'page_rank', 'status'],
      dtype='object')

In [64]:
df.value_counts()

url                                                                                                                             length_url  length_hostname  ip  nb_dots  nb_hyphens  nb_at  nb_qm  nb_and  nb_or  nb_eq  nb_underscore  nb_tilde  nb_percent  nb_slash  nb_star  nb_colon  nb_comma  nb_semicolumn  nb_dollar  nb_space  nb_www  nb_com  nb_dslash  http_in_path  https_token  ratio_digits_url  ratio_digits_host  punycode  port  tld_in_path  tld_in_subdomain  abnormal_subdomain  nb_subdomains  prefix_suffix  random_domain  shortening_service  path_extension  nb_redirection  nb_external_redirection  length_words_raw  char_repeat  shortest_words_raw  shortest_word_host  shortest_word_path  longest_words_raw  longest_word_host  longest_word_path  avg_words_raw  avg_word_host  avg_word_path  phish_hints  domain_in_brand  brand_in_subdomain  brand_in_path  suspecious_tld  statistical_report  nb_hyperlinks  ratio_intHyperlinks  ratio_extHyperlinks  ratio_nullHyperlinks  nb_extCSS  ratio_intRedirection  ratio_extRedirection  ratio_intErrors  ratio_extErrors  login_form  external_favicon  links_in_tags  submit_email  ratio_intMedia  ratio_extMedia  sfh  iframe  popup_window  safe_anchor  onmouseover  right_clic  empty_title  domain_in_title  domain_with_copyright  whois_registered_domain  domain_registration_length  domain_age  web_traffic  dns_record  google_index  page_rank  status
https://zrq2y.weblium.site/                                                                                                     27          18               0   2        0           0      0      0       0      0      0              0         0           3         0        1         0         0              0          0         0       0       0          0             0            0.037037          0.055556           0         0     0            0                 0                   2              0              0              0                   0               0               0                        2                 0            5                   5                   0                   7                  7                  0                  6.000000       6.000000       0.000000       1            0                0                   0              0               0                   48             0.812500             0.187500             0                     1          0                     0.222222              0                0.0              0           1                 64.705882      0             0.0             0.0             0    0       0             0.0          0            0           0            1                0                      1                        0                            1230       123186       0           1             2          phishing    1
http://00324il.moonfruit.com                                                                                                    28          21               0   2        0           0      0      0       0      0      0              0         0           2         0        1         0         0              0          0         0       0       0          0             1            0.178571          0.238095           0         0     0            0                 1                   2              0              0              1                   0               0               0                        2                 2            7                   7                   0                   9                  9                  0                  8.000000       8.000000       0.000000       0            0                0                   0              0               0                   36             0.750000             0.250000             0                     1          0                     0.000000              0                0.0              0           1                 72.000000      0             100.0           0.0             0    0       0             0.0          0            0           0            1                0                      0                        50                           7621       56198        0           1             6          phishing    1
http://02dfbe20-6956-4be6-ba22-36ae0e0d3053.htmlcomponentservice.com/get_draft?id=99ea0e_8eddaa8b0b3b6316a653bbd03eb5b48f.html  126         61               1   3        4           0      1      0       0      1      2              0         0           3         0        1         0         0              0          0         0       1       0          0             1            0.309524          0.327869           0         0     0            0                 1                   3              0              0              0                   0               0               0                        12                5            2                   4                   2                   32                 20                 32                 8.666667       8.666667       8.666667       0            0                0                   0              0               2                   37             0.000000             1.000000             0                     2          0                     0.027027              0                0.0              0           1                 0.000000       0             0.0             100.0           0    0       0             0.0          0            0           0            1                1                      0                        168                          1658       2580873      0           1             0          phishing    1
http://03418f6.netsolhost.com/FF7AADF203DF6C7A0B7C8A74B8164E55/                                                                 63          22               1   2        0           0      0      0       0      0      0              0         0           4         0        1         0         0              0          0         0       0       0          0             1            0.365079          0.272727           0         0     0            0                 1                   2              0              0              1                   0               0               0                        3                 3            7                   7                   32                  32                 10                 32                 16.333333      8.500000       32.000000      0            0                0                   0              0               0                   0              0.000000             0.000000             0                     0          0                     0.000000              0                0.0              0           0                 0.000000       0             0.0             0.0             0    0       0             0.0          0            0           1            1                0                      0                        61                           5783       50436        0           1             4          phishing    1
http://03418f6.netsolhost.com/FF7AADF203DF6C7A0B7C8A74B8164E55/?sec=Milka%20Gostovic                                            84          22               1   2        0           0      1      0       0      1      0              0         1           4         0        1         0         0              0          1         0       0       0          0             1            0.297619          0.272727           0         0     0            0                 1                   2              0              0              1                   0               0               0                        6                 3            3                   7                   3                   32                 10                 32                 11.166667      8.500000       12.500000      0            0                0                   0              0               0                   0              0.000000             0.000000             0                     0          0                     0.000000              0                0.0              0           0                 0.000000       0             0.0             0.0             0    0       0             0.0          0            0           1            1                0                      0                        59                           5784       50100        0           1             4          phishing    1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ..
http://0s.nrxwo2lo.ozvs4y3pnu.cmla.ru/?act=login                                                                                48          30               0   4        0           0      1      0       0      1      0              0         0           3         0        1         0         0              0          0         0       0       0          0             1            0.083333          0.133333           0         0     0            0                 0                   3              0              1              0                   0               3               0                        6                 0            2                   2                   3                   10                 10                 5                  5.333333       6.000000       4.000000       1            0                0                   0              0               0                   27             1.000000             0.000000             0                     0          0                     0.000000              0                0.0              0           0                 100.000000     0             0.0             0.0             0    0       0             0.0          0            0           0            1                0                      0                        124                          2797       0            0           1             1          phishing    1
http://0s.n5vs44tv.verek.ru/                                                                                                    28          20               0   3        0           0      0      0       0      0      0              0         0           3         0        1         0         0              0          0         0       0       0          0             1            0.142857          0.200000           0         0     0            0                 0                   3              0              0              0                   0               0               0                        3                 1            2                   2                   0                   8                  8                  0                  5.000000       5.000000       0.000000       0            0                0                   0              0               0                   228            0.991228             0.008772             0                     0          0                     2.000000              0                0.0              0           0                 100.000000     0             50.0            50.0            0    0       0             100.0        0            0           0            1                1                      0                        357                         -2          0            0           1             2          phishing    1
http://05.my03.com/login.php                                                                                                    28          11               0   3        0           0      0      0       0      0      0              0         0           3         0        1         0         0              0          0         0       0       0          0             1            0.142857          0.363636           0         0     0            0                 1                   3              0              0              0                   0               1               0                        4                 0            2                   2                   3                   5                  4                  5                  3.500000       3.000000       4.000000       1            0                0                   0              0               0                   103            0.932039             0.067961             0                     1          0                     0.285714              0                0.0              0           1                 81.818182      0             100.0           0.0             0    0       0             0.0          0            0           0            1                1                      0                        241                          7063       767936       1           1             2          phishing    1
http://04de5a73-bfcf-4a49-95ed-e4f8c3f51fde.htmlcomponentservice.com/get_draft?id=96c871_39d1eee16c26eff7fabe1ba646529cb6.html  126         61               1   3        4           0      1      0       0      1      2              0         0           3         0        1         0         0              0          0         0       1       0          0             1            0.285714          0.245902           0         0     0            0                 1                   3              0              0              0                   0               0               0                        12                4            2                   4                   2                   32                 20                 32                 8.666667       8.666667       8.666667       0            0                0                   0              0               2                   51             0.588235             0.411765             0                     1          0                     0.095238              0                0.0              0           1                 9.090909       0             50.0            50.0            0    0       0             100.0        0            0           0            1                0                      0                        168                          1659       2580873      0           1             0          phishing    1
http://03418f6.netsolhost.com/FF7AADF203DF6C7A0B7C8A74B8164E55?sec=Puc%20Kotsis                                                 79          22               1   2        0           0      1      0       0      1      0              0         1           3         0        1         0         0              0          1         0       0       0          0             1            0.316456          0.272727           0         0     0            0                 1                   2              0              0              1                   0               1               0                        6                 3            3                   7                   3                   32                 10                 32                 10.500000      8.500000       11.500000      0            0                0                   0              0               0                   0              0.000000             0.000000             0                     0          0                     0.000000              0                0.0              0           0                 0.000000       0             0.0             0.0             0    0       0             0.0          0            0           1            1                0                      0                        61                           5783       50436        0           1             4          phishing    1
Name: count, Length: 11430, dtype: int64

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11430 entries, 0 to 11429
Data columns (total 89 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   url                         11430 non-null  object
 1   length_url                  11430 non-null  int64
 2   length_hostname             11430 non-null  int64
 3   ip                          11430 non-null  int64
 4   nb_dots                     11430 non-null  int64
 5   nb_hyphens                  11430 non-null  int64
 6   nb_at                       11430 non-null  int64
 7   nb_qm                       11430 non-null  int64
 8   nb_and                      11430 non-null  int64
 9   nb_or                       11430 non-null  int64
 10  nb_eq                       11430 non-null  int64
 11  nb_underscore               11430 non-null  int64
 12  nb_tilde                    11430 non-null  int64
 13  nb_percent                  11430 non-null  int64
 14  nb_slash                    11430 non-null  int64
 15  nb_star                     11430 non-null  int64
 16  nb_colon                    11430 non-null  int64
 17  nb_comma                    11430 non-null  int64
 18  nb_semicolumn               11430 non-null  int64
 19  nb_dollar                   11430 non-null  int64
 20  nb_space                    11430 non-null  int64
 21  nb_www                      11430 non-null  int64
 22  nb_com                      11430 non-null  int64
 23  nb_dslash                   11430 non-null  int64
 24  http_in_path                11430 non-null  int64
 25  https_token                 11430 non-null  int64
 26  ratio_digits_url            11430 non-null  float64
 27  ratio_digits_host           11430 non-null  float64
 28  punycode                    11430 non-null  int64
 29  port                        11430 non-null  int64
 30  tld_in_path                 11430 non-null  int64
 31  tld_in_subdomain            11430 non-null  int64
 32  abnormal_subdomain          11430 non-null  int64
 33  nb_subdomains               11430 non-null  int64
 34  prefix_suffix               11430 non-null  int64
 35  random_domain               11430 non-null  int64
 36  shortening_service          11430 non-null  int64
 37  path_extension              11430 non-null  int64
 38  nb_redirection              11430 non-null  int64
 39  nb_external_redirection     11430 non-null  int64
 40  length_words_raw            11430 non-null  int64
 41  char_repeat                 11430 non-null  int64
 42  shortest_words_raw          11430 non-null  int64
 43  shortest_word_host          11430 non-null  int64
 44  shortest_word_path          11430 non-null  int64
 45  longest_words_raw           11430 non-null  int64
 46  longest_word_host           11430 non-null  int64
 47  longest_word_path           11430 non-null  int64
 48  avg_words_raw               11430 non-null  float64
 49  avg_word_host               11430 non-null  float64
 50  avg_word_path               11430 non-null  float64
 51  phish_hints                 11430 non-null  int64
 52  domain_in_brand             11430 non-null  int64
 53  brand_in_subdomain          11430 non-null  int64
 54  brand_in_path               11430 non-null  int64
 55  suspecious_tld              11430 non-null  int64
 56  statistical_report          11430 non-null  int64
 57  nb_hyperlinks               11430 non-null  int64
 58  ratio_intHyperlinks         11430 non-null  float64
 59  ratio_extHyperlinks         11430 non-null  float64
 60  ratio_nullHyperlinks        11430 non-null  int64
 61  nb_extCSS                   11430 non-null  int64
 62  ratio_intRedirection        11430 non-null  int64
 63  ratio_extRedirection        11430 non-null  float64
 64  ratio_intErrors             11430 non-null  int64
 65  ratio_extErrors             11430 non-null  float64
 66  login_form                  11430 non-null  int64
 67  external_favicon            11430 non-null  int64
 68  links_in_tags               11430 non-null  float64
 69  submit_email                11430 non-null  int64
 70  ratio_intMedia              11430 non-null  float64
 71  ratio_extMedia              11430 non-null  float64
 72  sfh                         11430 non-null  int64
 73  iframe                      11430 non-null  int64
 74  popup_window                11430 non-null  int64
 75  safe_anchor                 11430 non-null  float64
 76  onmouseover                 11430 non-null  int64
 77  right_clic                  11430 non-null  int64
 78  empty_title                 11430 non-null  int64
 79  domain_in_title             11430 non-null  int64
 80  domain_with_copyright       11430 non-null  int64
 81  whois_registered_domain     11430 non-null  int64
 82  domain_registration_length  11430 non-null  int64
 83  domain_age                  11430 non-null  int64
 84  web_traffic                 11430 non-null  int64
 85  dns_record                  11430 non-null  int64
 86  google_index                11430 non-null  int64
 87  page_rank                   11430 non-null  int64
 88  status                      11430 non-null  object
dtypes: float64(13), int64(74), object(2)
memory usage: 7.8+ MB

In [66]:
from sklearn.model_selection import train_test_split

# Drop 'url' column only if it exists, to prevent KeyError on re-runs
if "url" in df.columns:
    df = df.drop("url",axis=1)

x=df.drop("status",axis=1)
y=df["status"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(9144, 87) (9144,)
(2286, 87) (2286,)

In [67]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, mean_squared_error, mean_absolute_error, r2_score

In [68]:
!pip install catboost --quiet

In [69]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

logreg = LogisticRegression(max_iter=5000)
logreg.fit(x_train_scaled, y_train)
y_pred_lr = logreg.predict(x_test_scaled)


y_pred_lr_enc = pd.Series(y_pred_lr).map({'legitimate': 0, 'phishing': 1})
print("metric of logistic regression")
print("Accuracy: ", accuracy_score(y_test, y_pred_lr))
print("Precision: ", precision_score(y_test, y_pred_lr, pos_label='phishing'))
print("Recall: ", recall_score(y_test, y_pred_lr, pos_label='phishing'))
print("F1 score: ", f1_score(y_test, y_pred_lr, pos_label='phishing'))
print("rsmne:", np.sqrt(mean_squared_error(y_test_enc, y_pred_lr_enc)))
print("mae:", mean_absolute_error(y_test_enc, y_pred_lr_enc))
print("r2 score:", r2_score(y_test_enc, y_pred_lr_enc))

metric of logistic regression
Accuracy:  0.9479440069991251
Precision:  0.9503484320557491
Recall:  0.9462272333044233
F1 score:  0.9482833550630161
rsmne: 0.22815782476363788
mae: 0.05205599300087489
r2 score: 0.7917600886133798

In [70]:
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
y_pred_dt = dt.predict(x_test)


y_pred_dt_enc = pd.Series(y_pred_dt).map({'legitimate': 0, 'phishing': 1})
print("metric for decision tree")
print("Accuracy: ", accuracy_score(y_test, y_pred_dt))
print("Precision: ", precision_score(y_test, y_pred_dt, pos_label='phishing'))
print("Recall: ", recall_score(y_test, y_pred_dt, pos_label='phishing'))
print("F1 score: ", f1_score(y_test, y_pred_dt, pos_label='phishing'))
print("rsmne:", np.sqrt(mean_squared_error(y_test_enc, y_pred_dt_enc)))
print("mae:", mean_absolute_error(y_test_enc, y_pred_dt_enc))
print("r2 score:", r2_score(y_test_enc, y_pred_dt_enc))

metric for decision tree
Accuracy:  0.9365704286964129
Precision:  0.9315068493150684
Recall:  0.9436253252385083
F1 score:  0.9375269280482551
rsmne: 0.2518522807194468
mae: 0.06342957130358705
r2 score: 0.7462622928482359

In [71]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
y_pred_rf = rf.predict(x_test)


y_pred_rf_enc = pd.Series(y_pred_rf).map({'legitimate': 0, 'phishing': 1})
print("metric for Random Forest")
print("Accuracy: ", accuracy_score(y_test, y_pred_rf))
print("Precision: ", precision_score(y_test, y_pred_rf, pos_label='phishing'))
print("Recall: ", recall_score(y_test, y_pred_rf, pos_label='phishing'))
print("F1 score: ", f1_score(y_test, y_pred_rf, pos_label='phishing'))
print("rsmne:", np.sqrt(mean_squared_error(y_test_enc, y_pred_rf_enc)))
print("mae:", mean_absolute_error(y_test_enc, y_pred_rf_enc))
print("r2 score:", r2_score(y_test_enc, y_pred_rf_enc))

metric for Random Forest
Accuracy:  0.9654418197725284
Precision:  0.9645328719723183
Recall:  0.9670424978317432
F1 score:  0.9657860545690775
rsmne: 0.18589830614470795
mae: 0.03455818022747156
r2 score: 0.8617566974828319

In [72]:
from lightgbm import LGBMClassifier

import numpy as np


y_train_enc = y_train.map({'legitimate': 0, 'phishing': 1})
y_test_enc = y_test.map({'legitimate': 0, 'phishing': 1})


lgb_model = LGBMClassifier(random_state=42, verbose=-1)
lgb_model.fit(x_train, y_train_enc)


lgb_preds = lgb_model.predict(x_test)
print("metrics for LightGBM")
print(f"Accuracy:  {accuracy_score(y_test_enc, lgb_preds):.5f}")
print(f"Precision: {precision_score(y_test_enc, lgb_preds):.5f}")
print(f"Recall:    {recall_score(y_test_enc, lgb_preds):.5f}")
print(f"F1 Score:  {f1_score(y_test_enc, lgb_preds):.5f}")
print(f"RMSE:      {np.sqrt(mean_squared_error(y_test_enc, lgb_preds)):.5f}")
print(f"MAE:       {mean_absolute_error(y_test_enc, lgb_preds):.5f}")
print(f"R2 Score:  {r2_score(y_test_enc, lgb_preds):.5f}")

metrics for LightGBM
Accuracy:  0.96982
Precision: 0.97049
Recall:    0.96964
F1 Score:  0.97007
RMSE:      0.17373
MAE:       0.03018
R2 Score:  0.87926

In [73]:
from xgboost import XGBClassifier

y_train_enc = y_train.map({'legitimate': 0, 'phishing': 1})
y_test_enc = y_test.map({'legitimate': 0, 'phishing': 1})


xgb_model = XGBClassifier(random_state=42, eval_metric='logloss')
xgb_model.fit(x_train, y_train_enc)


xgb_preds = xgb_model.predict(x_test)
print("metric for XGBoost")
print(f"Accuracy:  {accuracy_score(y_test_enc, xgb_preds):.5f}")
print(f"Precision: {precision_score(y_test_enc, xgb_preds):.5f}")
print(f"Recall:    {recall_score(y_test_enc, xgb_preds):.5f}")
print(f"F1 Score:  {f1_score(y_test_enc, xgb_preds):.5f}")
print(f"RMSE:      {np.sqrt(mean_squared_error(y_test_enc, xgb_preds)):.5f}")
print(f"MAE:       {mean_absolute_error(y_test_enc, xgb_preds):.5f}")
print(f"R2 Score:  {r2_score(y_test_enc, xgb_preds):.5f}")

metric for XGBoost
Accuracy:  0.96894
Precision: 0.96638
Recall:    0.97225
F1 Score:  0.96930
RMSE:      0.17623
MAE:       0.03106
R2 Score:  0.87576

In [74]:
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, mean_squared_error, mean_absolute_error, r2_score
import numpy as np


y_train_enc = y_train.map({'legitimate': 0, 'phishing': 1})
y_test_enc = y_test.map({'legitimate': 0, 'phishing': 1})


cat_model = CatBoostClassifier(random_state=42, verbose=0)
cat_model.fit(x_train, y_train_enc)


cat_preds = cat_model.predict(x_test)


print(" metric for CatBoost ")
print(f"Accuracy:  {accuracy_score(y_test_enc, cat_preds):.5f}")
print(f"Precision: {precision_score(y_test_enc, cat_preds):.5f}")
print(f"Recall:    {recall_score(y_test_enc, cat_preds):.5f}")
print(f"F1 Score:  {f1_score(y_test_enc, cat_preds):.5f}")
print(f"RMSE:      {np.sqrt(mean_squared_error(y_test_enc, cat_preds)):.5f}")
print(f"MAE:       {mean_absolute_error(y_test_enc, cat_preds):.5f}")
print(f"R2 Score:  {r2_score(y_test_enc, cat_preds):.5f}")

 metric for CatBoost
Accuracy:  0.96894
Precision: 0.96880
Recall:    0.96964
F1 Score:  0.96922
RMSE:      0.17623
MAE:       0.03106
R2 Score:  0.87576

In [75]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, r2_score


y_train_enc = y_train.map({'legitimate': 0, 'phishing': 1})
y_test_enc = y_test.map({'legitimate': 0, 'phishing': 1})


et_model = ExtraTreesClassifier(random_state=42, n_jobs=-1)
et_model.fit(x_train, y_train_enc)


et_preds = et_model.predict(x_test)


print("metric for Extra Trees")
print(f"Accuracy:  {accuracy_score(y_test_enc, et_preds):.5f}")
print(f"Precision: {precision_score(y_test_enc, et_preds):.5f}")
print(f"Recall:    {recall_score(y_test_enc, et_preds):.5f}")
print(f"F1 Score:  {f1_score(y_test_enc, et_preds):.5f}")
print(f"RMSE:      {root_mean_squared_error(y_test_enc, et_preds):.5f}")
print(f"MAE:       {mean_absolute_error(y_test_enc, et_preds):.5f}")
print(f"R2 Score:  {r2_score(y_test_enc, et_preds):.5f}")

metric for Extra Trees
Accuracy:  0.96850
Precision: 0.97288
Recall:    0.96444
F1 Score:  0.96864
RMSE:      0.17747
MAE:       0.03150
R2 Score:  0.87401

In [76]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, r2_score


y_train_enc = y_train.map({'legitimate': 0, 'phishing': 1})
y_test_enc = y_test.map({'legitimate': 0, 'phishing': 1})


hgb_model = HistGradientBoostingClassifier(random_state=42)
hgb_model.fit(x_train, y_train_enc)


hgb_preds = hgb_model.predict(x_test)


print("metric for Hist Gradient Boosting ")
print(f"Accuracy:  {accuracy_score(y_test_enc, hgb_preds):.5f}")
print(f"Precision: {precision_score(y_test_enc, hgb_preds):.5f}")
print(f"Recall:    {recall_score(y_test_enc, hgb_preds):.5f}")
print(f"F1 Score:  {f1_score(y_test_enc, hgb_preds):.5f}")
print(f"RMSE:      {root_mean_squared_error(y_test_enc, hgb_preds):.5f}")
print(f"MAE:       {mean_absolute_error(y_test_enc, hgb_preds):.5f}")
print(f"R2 Score:  {r2_score(y_test_enc, hgb_preds):.5f}")

metric for Hist Gradient Boosting
Accuracy:  0.96850
Precision: 0.96797
Recall:    0.96964
F1 Score:  0.96880
RMSE:      0.17747
MAE:       0.03150
R2 Score:  0.87401

In [77]:
model_performance = [
    {
        "Model": "Logistic Regression",
        "Accuracy": 0.94794,
        "Precision": 0.95035,
        "Recall": 0.94623,
        "F1 Score": 0.94828,
        "RMSE": 0.22816,
        "MAE": 0.05206,
        "R2 Score": 0.79176
    },
    {
        "Model": "Decision Tree",
        "Accuracy": 0.93307,
        "Precision": 0.93029,
        "Recall": 0.93755,
        "F1 Score": 0.93391,
        "RMSE": 0.25871,
        "MAE": 0.06693,
        "R2 Score": 0.73226
    },
    {
        "Model": "Random Forest",
        "Accuracy": 0.96544,
        "Precision": 0.96453,
        "Recall": 0.96704,
        "F1 Score": 0.96579,
        "RMSE": 0.18590,
        "MAE": 0.03456,
        "R2 Score": 0.86176
    },
    {
        "Model": "LightGBM",
        "Accuracy": 0.96982,
        "Precision": 0.97049,
        "Recall": 0.96964,
        "F1 Score": 0.97007,
        "RMSE": 0.17373,
        "MAE": 0.03018,
        "R2 Score": 0.87926
    },
    {
        "Model": "XGBoost",
        "Accuracy": 0.96894,
        "Precision": 0.96638,
        "Recall": 0.97225,
        "F1 Score": 0.96930,
        "RMSE": 0.17623,
        "MAE": 0.03106,
        "R2 Score": 0.87576
    },
    {
        "Model": "CatBoost",
        "Accuracy": 0.96894,
        "Precision": 0.96880,
        "Recall": 0.96964,
        "F1 Score": 0.96922,
        "RMSE": 0.17623,
        "MAE": 0.03106,
        "R2 Score": 0.87576
    },
    {
        "Model": "Extra Trees",
        "Accuracy": 0.96850,
        "Precision": 0.97288,
        "Recall": 0.96444,
        "F1 Score": 0.96864,
        "RMSE": 0.17747,
        "MAE": 0.03150,
        "R2 Score": 0.87401
    },
    {
        "Model": "Hist Gradient Boosting",
        "Accuracy": 0.96850,
        "Precision": 0.96797,
        "Recall": 0.96964,
        "F1 Score": 0.96880,
        "RMSE": 0.17747,
        "MAE": 0.03150,
        "R2 Score": 0.87401
    }
]

performance_df = pd.DataFrame(model_performance)
performance_df = performance_df.set_index('Model')


performance_df = performance_df.sort_values(by='Accuracy', ascending=False)
display(performance_df)

,Accuracy,Precision,Recall,F1 Score,RMSE,MAE,R2 Score
Model,,,,,,,
LightGBM,0.96982,0.97049,0.96964,0.97007,0.17373,0.03018,0.87926
XGBoost,0.96894,0.96638,0.97225,0.96930,0.17623,0.03106,0.87576
CatBoost,0.96894,0.96880,0.96964,0.96922,0.17623,0.03106,0.87576
Extra Trees,0.96850,0.97288,0.96444,0.96864,0.17747,0.03150,0.87401
Hist Gradient Boosting,0.96850,0.96797,0.96964,0.96880,0.17747,0.03150,0.87401
Random Forest,0.96544,0.96453,0.96704,0.96579,0.18590,0.03456,0.86176
Logistic Regression,0.94794,0.95035,0.94623,0.94828,0.22816,0.05206,0.79176
Decision Tree,0.93307,0.93029,0.93755,0.93391,0.25871,0.06693,0.73226